import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useCart } from '@/hooks/useCart'
import { useCreateOrder } from '@/hooks/useCreateOrder'
import { useRetryPayment } from '@/hooks/useRetryPayment'
import { useRazorpayCheckout } from '@/features/checkout/useRazorpayCheckout'
import { ShippingForm } from '@/features/checkout/ShippingForm'
import { CheckoutCartSummary } from '@/features/checkout/CheckoutCartSummary'
import { OrderPendingPayment } from '@/features/checkout/OrderPendingPayment'
import { Alert } from '@/components/ui/Alert'
import { Skeleton } from '@/components/ui/Skeleton'
import { getApiErrorMessage } from '@/utils/apiError'
import { orderDetailPath } from '@/constants/routes'
import type { ShippingFormValues } from '@/schemas/checkout.schema'
import type { CheckoutOrderView } from '@/types/checkout'
import styles from './CheckoutPage.module.css'

/**
 * Behind ProtectedRoute (App.tsx). One Idempotency-Key per page mount
 * (§13.G) — every retry of a stuck/failed checkout attempt during this
 * mount reuses it, which is what makes a double-click on "Pay now" safe;
 * a fresh key is only generated by actually remounting this page (e.g.
 * navigating away and back). Lazy useState initializer, not a plain
 * variable, so it survives re-renders without recomputing.
 */
export function CheckoutPage() {
  const navigate = useNavigate()
  const [idempotencyKey] = useState(() => crypto.randomUUID())
  const [order, setOrder] = useState<CheckoutOrderView | null>(null)
  const [paymentError, setPaymentError] = useState<string | null>(null)

  const { data: cart, isPending: isCartPending, isError: isCartError, error: cartError } = useCart()
  const createOrder = useCreateOrder()
  const retryPayment = useRetryPayment()

  const { openCheckout, isOpening, isVerifying } = useRazorpayCheckout({
    // Never render "payment confirmed" here — only navigate. The
    // confirmation page re-fetches the order and renders strictly off its
    // own status field, which is what stays correct if the webhook
    // disagrees with this call (§13.G).
    onVerified: (result) => void navigate(orderDetailPath(result.orderId), { replace: true }),
    onDismissed: () =>
      setPaymentError('Payment was not completed. Your order is still here — you can retry anytime.'),
    onError: setPaymentError,
  })

  async function startPayment(target: CheckoutOrderView) {
    setPaymentError(null)
    try {
      const payment = await retryPayment.mutateAsync(target.id)
      await openCheckout(
        payment,
        { orderNumber: target.orderNumber },
        { name: target.shippingRecipientName, contact: target.shippingPhone },
      )
    } catch (err) {
      setPaymentError(getApiErrorMessage(err))
    }
  }

  async function handleSubmitShipping(values: ShippingFormValues) {
    setPaymentError(null)
    try {
      const created = await createOrder.mutateAsync({
        payload: { ...values, shippingAddressLine2: values.shippingAddressLine2 || undefined },
        idempotencyKey,
      })
      setOrder(created)
      await startPayment(created)
    } catch {
      // createOrder.isError below renders the message — nothing else to do.
    }
  }

  function handleRetry() {
    if (order) {
      void startPayment(order)
    }
  }

  if (isCartPending) {
    return (
      <section className={styles.wrap}>
        <h1>Checkout</h1>
        <Skeleton className={styles.skeletonBlock} />
      </section>
    )
  }

  if (isCartError) {
    return (
      <section className={styles.wrap}>
        <h1>Checkout</h1>
        <Alert variant="error">{getApiErrorMessage(cartError)}</Alert>
      </section>
    )
  }

  if (order) {
    return (
      <section className={styles.wrap}>
        <h1>Checkout</h1>
        <OrderPendingPayment
          order={order}
          error={paymentError}
          onRetry={handleRetry}
          isProcessing={retryPayment.isPending || isOpening || isVerifying}
        />
      </section>
    )
  }

  if (cart.items.length === 0) {
    return (
      <section className={styles.wrap}>
        <h1>Checkout</h1>
        <Alert variant="info">Your cart is empty — add something before checking out.</Alert>
      </section>
    )
  }

  const hasUnavailableItems = cart.items.some((item) => !item.isAvailable)
  if (hasUnavailableItems) {
    return (
      <section className={styles.wrap}>
        <h1>Checkout</h1>
        <Alert variant="error">
          Remove the unavailable item(s) in your cart before checking out.
        </Alert>
      </section>
    )
  }

  return (
    <section className={styles.wrap}>
      <h1>Checkout</h1>
      <div className={styles.layout}>
        <div className={styles.formColumn}>
          {createOrder.isError && <Alert variant="error">{getApiErrorMessage(createOrder.error)}</Alert>}
          <ShippingForm
            onSubmit={(values) => void handleSubmitShipping(values)}
            isSubmitting={createOrder.isPending || retryPayment.isPending || isOpening}
          />
        </div>
        <CheckoutCartSummary cart={cart} />
      </div>
    </section>
  )
}
